server {
  listen 80;

  root /usr/share/nginx/html;

  location /healthz {
    add_header Content-Type text/plain;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
